version: '2'
services:
    apache2:
        image: webdevops/apache:latest        
        volumes:
            - ./IntegracionContinua:/var/www/html
        ports:
            - 80:80
            - 443:443
        
